(function() {
	window.eocourse = window.eocourse || {};
	window.eocourse.sidebarConstant = {
		id: 'sidebar_js',
		list: [{
			title: '欢迎使用',
			sref: 'index',
			href: '/md/index'
		}, {
			title: '接口管理',
			sref: '接口管理',
			childList: [{
				title: '简介',
				sref: '接口管理.简介',
				href: '/md/接口管理/简介'
			}, {
				title: '快速入门',
				sref: '接口管理.快速入门',
				childList: [{
					title: '创建项目',
					sref: '接口管理.快速入门.创建项目',
					href: '/md/接口管理/快速入门/创建项目'
				}, {
					title: '创建接口',
					sref: '接口管理.快速入门.创建接口',
					href: '/md/接口管理/快速入门/创建接口'
				}, {
					title: '项目概况',
					sref: '接口管理.快速入门.测试接口',
					href: '/md/接口管理/快速入门/测试接口'
				}, {
					title: '添加团队成员',
					sref: '接口管理.快速入门.添加团队成员',
					href: '/md/接口管理/项目管理/添加团队成员'
				}, {
					title: '在线分享项目',
					sref: '接口管理.快速入门.在线分享项目',
					href: '/md/接口管理/快速入门/在线分享项目'
				}]
			}, {
				title: '项目管理',
				sref: '接口管理.项目管理',
				childList: [{
					title: '创建项目',
					sref: '接口管理.项目管理.创建项目',
					href: '/md/接口管理/项目管理/创建项目'
				}, {
					title: '修改/删除项目',
					sref: '接口管理.项目管理.修改删除项目',
					href: '/md/接口管理/项目管理/修改删除项目'
				}, {
					title: '项目概况',
					sref: '接口管理.项目管理.项目概况',
					href: '/md/接口管理/项目管理/项目概况'
				}, {
					title: '添加团队成员',
					sref: '接口管理.项目管理.添加团队成员',
					href: '/md/接口管理/项目管理/添加团队成员'
				}, {
					title: '在线分享项目',
					sref: '接口管理.项目管理.在线分享项目',
					href: '/md/接口管理/项目管理/在线分享项目'
				}]
			}]
		}, {
			title: '接口管理-开源版本',
			sref: '开源版本',
			childList: [{
				title: '简介',
				sref: '开源版本.简介',
				href: '/md/开源版本/简介'
			}, {
				title: '部署指南',
				sref: '开源版本.部署指南',
				href: '/md/开源版本/部署指南'
			}, {
				title: '更新日志',
				sref: '开源版本.更新日志',
				href: '/md/开源版本/更新日志'
			}, {
				title: '常见问题',
				sref: '开源版本.常见问题',
				href: '/md/开源版本/常见问题'
			}]
		}, {
			title: '接口商店',
			sref: '接口商店',
			childList: [{
				title: '常见问题',
				sref: '接口商店.常见问题',
				href: '/md/接口商店/常见问题'
			}, {
				title: '身份认证',
				sref: '接口商店.身份认证',
				href: '/md/接口商店/身份认证'
			}, {
				title: '应用认证',
				sref: '接口商店.应用认证',
				href: '/md/接口商店/应用认证'
			}, {
				title: '使用流程',
				sref: '接口商店.AS使用流程',
				href: '/md/接口商店/AS使用流程'
			}, {
				title: '短信API使用流程',
				sref: '接口商店.短信API使用流程',
				href: '/md/接口商店/短信API使用流程'
			}, {
				title: '群发短信使用流程',
				sref: '接口商店.群发短信使用流程',
				href: '/md/接口商店/群发短信使用流程'
			}]
		}, {
			title: '用户',
			sref: '用户',
			childList: [{
				title: '基本账户操作',
				sref: '用户.基本账户操作',
				childList: [{
					title: '用户注册',
					sref: '用户.基本账户操作.注册',
					href: '/md/用户/基本账户操作/注册'
				}, {
					title: '用户登录',
					sref: '用户.基本账户操作.登录',
					href: '/md/用户/基本账户操作/登录'
				}, {
					title: '完善个人资料',
					sref: '用户.基本账户操作.完善个人资料',
					href: '/md/用户/基本账户操作/完善个人资料'
				}, {
					title: '修改密码',
					sref: '用户.基本账户操作.修改密码',
					href: '/md/用户/基本账户操作/修改密码'
				}, {
					title: '忘记密码',
					sref: '用户.基本账户操作.忘记密码',
					href: '/md/用户/基本账户操作/忘记密码'
				}]
			}]
		}]
	};
})()